// TODO Components
export const TODO_COMPONENTS_FETCH_REQUEST = 'TODO_COMPONENTS_FETCH_REQUEST';
export const TODO_COMPONENTS_FETCH_SUCCESS = 'TODO_COMPONENTS_FETCH_SUCCESS';
export const TODO_COMPONENTS_FETCH_FAILED = 'TODO_COMPONENTS_FETCH_FAILED';

export const TODO_COMPONENT_CREATE_SUCCESS = 'TODO_COMPONENT_CREATE_SUCCESS';
export const TODO_COMPONENT_CREATE_FAILED = 'TODO_COMPONENT_CREATE_FAILED';

export const TODO_COMPONENT_EDIT_SUCCESS = 'TODO_COMPONENT_EDIT_SUCCESS';
export const TODO_COMPONENT_EDIT_FAILED = 'TODO_COMPONENT_EDIT_FAILED';

export const TODO_COMPONENT_DELETE_SUCCESS = 'TODO_COMPONENT_DELETE_SUCCESS';
export const TODO_COMPONENT_DELETE_FAILED = 'TODO_COMPONENT_DELETE_FAILED';